site_name: CSC computing and data environment
pages:
  - Home: 'index.md'
  - Accounts: 'accounts.md'
  - Connecting: 'connecting.md'
  - Computing: 'computing.md'
  - Cloud: 'cloud.md'
  - Data: 'data.md'
  - Applications: 'applications.md'
  - Support: 'support.md'
  - All articles:
    - articles/csd.md
    - articles/fgci-guide-intro.md
    - articles/gromacs.md
    - articles/maestro.md
    - articles/rspatial-env.md
    - articles/rspatial-env2.md    
theme:
  name: readthedocs
extra_css:
  - css/extra.css
extra_javascript:
  - https://use.fontawesome.com/e51b07f7f1.js
markdown_extensions:
  - admonition
  - attr_list
